### DISCUSSION TITLE
Add some informations in reports

### DISCUSSION THREAD

**Discussion by MMALPST** [gianlucam76/k8s-cleaner#293] [Ideas]
Hi,

First of all, i would like to congratulate you for this wonderful tool, really useful and easy to use !
I would like to share some idea i got using k8s cleaner, would it be possible to include phase of the object match in the generated report ? 
I mean, for example : when a pod is supposed to be cleaned, it would show if it was pending, or failed, or in progress in the report, currently there is only a message with timestamp and resource name.

Best regards

**Comment by gianlucam76** [comment]
Thank you @MMALPST. I will add that. 

When you pass a Lua method in the Cleaner instance, on top of saying whether a resource is a match or not, you can return a message. For instance [here](https://github.com/gianlucam76/k8s-cleaner/blob/3c0d0454b479bdf2497929badede543c828a5be6/examples-unhealthy-resources/pod-with-outdated-secrets/pods-with-outdated-secret-data.yaml#L181)

Right now the message is only printed in the logs.

I will enhance to report the message in the final report as well. 

That way anybody can put in the message anything that is meaningful and it is inline with cleaner philosophy.

**Comment by MMALPST** [comment]
Thanks for your quick answer !

**Comment by gianlucam76** [comment]
I tried this and it is already possibile.  Just add the message field when a resource is a message. And it will be reported back by Cleaner.

For instance, in [this example ](https://github.com/gianlucam76/k8s-cleaner/blob/main/examples-unused-resources/configmaps/orphaned_configmaps.yaml) I added **message**:

```yaml
        for _, configMap in ipairs(configMaps) do
          key = getKey(configMap.metadata.namespace,configMap.metadata.name)
          if not podConfigMaps[key] then
            table.insert(unusedConfigMaps, {message= "this is a test", resource = configMap})
          end
        end
```        

The cleaner report contains the message

```yaml
    resourceInfo:
    - message: 'this is a test. time: 2025-05-24 08:43:00.481262425 +0000 UTC m=+723.638360414'
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kube-root-ca.crt
        namespace: default
``` 

Same if I look for instance for [completed Jobs](https://github.com/gianlucam76/k8s-cleaner/blob/main/examples-unused-resources/jobs/completed_jobs.yaml)

By adding 

```yaml
            if obj.status.completionTime ~= nil and obj.status.succeeded > 0 then
              hs.matching = true
              hs.message = "ok this job is completed"
            end
```
            
the report is 

```yaml
    - message: 'ok this job is completed. time: 2025-05-24 08:56:00.313045466 +0000
        UTC m=+335.898876488'
      resource:
        apiVersion: batch/v1
        kind: Job
        name: test-job
        namespace: foo
    - message: 'ok this job is completed. time: 2025-05-24 08:56:00.313045466 +0000
        UTC m=+335.898876488'
      resource:
        apiVersion: batch/v1
        kind: Job
        name: test-job
        namespace: bar
```

**Comment by theopeudupin** [comment]
Hello @gianlucam76

We set custom message on our Cleaner following your example. It works really great !

It's a detail but Im wondering if it would make more sens to have the time in a seperate field from 'message' ?

```
    - message: 'ok this job is completed.'
      time: '2025-05-24 08:56:00.313045466 +0000 UTC m=+335.898876488'
      resource:
        apiVersion: batch/v1
        kind: Job
        name: test-job
        namespace: foo
```

instead of : 

```
    - message: 'ok this job is completed. time: 2025-05-24 08:56:00.313045466 +0000'
        UTC m=+335.898876488'
      resource:
        apiVersion: batch/v1
        kind: Job
        name: test-job
        namespace: foo
```
