### ISSUE TITLE
Cleaner instance for Terminating Pods

### ISSUE THREAD

**Issue by aminmr** [gianlucam76/k8s-cleaner#127]
Hi,
I’m trying to implement a cleaner for terminating pods in my Kubernetes cluster using this project. However, I’ve tried several approaches, and none of them seem to work effectively.

## What I’ve Tried:
```yaml
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: completed-pods
spec:
  schedule: "*/5 * * * *"
  resourcePolicySet:
    resourceSelectors:
    - kind: Pod
      group: ""
      version: v1
      evaluate: |
        function evaluate()
          hs = {}
          hs.matching = false

          -- Check if the pod has a deletionTimestamp field (i.e., pod is terminating)
          if obj.metadata.deletionTimestamp ~= nill then
            -- If deletionTimestamp has a value, the pod is terminating
            hs.matching = true
          end

          return hs
        end
  action: Scan
```
It seems like I’m missing something or not handling pod termination conditions correctly.

## My Objective:
I want to remove pods that are stuck in the terminating state for a certain period of time (e.g., more than 5 minutes).

Could you provide any advice or sample code to help me write this cleaner for terminating pods?
Any help or guidance would be greatly appreciated!
