### ISSUE TITLE
BUG: Deleting Cleaner instance does not remove associated Report

### ISSUE THREAD

**Issue by gianlucam76** [gianlucam76/k8s-cleaner#41]
# Problem Description

Create a Cleaner instance with

```yaml
  notifications:
  - name: report
    type: CleanerReport
```

A Report instance is generated. When cleaner instance is deleted, expectation is that Report is also removed. 

But Report instance is not removed.
