### ISSUE TITLE
labelSelector support for namespaces

### ISSUE THREAD

**Issue by ctrought** [gianlucam76/k8s-cleaner#52]
**Is your feature request related to a problem? Please describe.**
I would like to target a range of namespaces based on a label instead of defining many resourceSelectors for each individual namespace

```
    resourceSelectors:
    - namespace: namespace-1
      kind: Secret
      group: ""
      version: v1
    - namespace: namespace-2
      kind: Secret
      group: ""
      version: v1
    - namespace: namespace-3
      kind: Secret
      group: ""
      version: v1
...
...
```

**Describe the solution you'd like**
It would be nice to support labelSelector on the namespace field.

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#LabelSelector

This could potentially look like this.
_labelSelector.matchExpressions_
```
    resourceSelectors:
    - kind: Secret
      group: ""
      version: v1
      namespaceSelector:
        matchExpressions:
        - key: tenant
          operator: In
          values: ["marketing", "finance", "operations"]
```
_labelSelector.matchLabels_
```
    resourceSelectors:
    - kind: Secret
      group: ""
      version: v1
      namespaceSelector:
        matchLabels:
          tenant: marketing
```

Or the namespaceSelector might be better to have as a direct child of resourcePolicySet since resourceSelector already have label filtering and targets the actual resource. It would probably also be helpful to use native labelSelectors on the resources.

```
  resourcePolicySet:
    resourceSelectors:
    - kind: Secret
      group: ""
      version: v1
    namespaceSelector:
      matchExpressions:
      - key: tenant
        operator: In
        values: ["marketing", "finance", "operations"]
```

**Describe alternatives you've considered**
Building into a lua to filter namespaces, and then filter and other resources being targeted to see whether they are in the list of filtered namespaces. However selecting namespaces by a label is likely a common requirement so it would be handy to have it built into k8s cleaner resourceSelector.

**Additional context**
Very nice project, we've been looking for something exactly like k8s-cleaner! Thank you! 🙏

**Comment by gianlucam76** [comment]
Thank you for submitting this request. I agree it's needed and it should be relatively easy to add it. Will add this enhancement.

Thanks

**Comment by gianlucam76** [comment]
Implemented [here](https://github.com/gianlucam76/k8s-cleaner/pull/53)

To select deployments from namespaces with labels "key1=value1" and key2=value2"

```yaml
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: cleaner-sample1
spec:
  schedule: "* 0 * * *" # Executes every day at midnight
  resourcePolicySet:
    resourceSelectors:
    - kind: Deployment
      group: "apps"
      version: v1
      namespaceSelector: "key1=value1, key2=value2"  
  action: Delete # Deletes matching Deployments
 ```
