### ISSUE TITLE
Cleaner Report resource deletion conditions

### ISSUE THREAD

**Issue by ctrought** [gianlucam76/k8s-cleaner#62]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to expire objects based on a set of predefined conditions that can easily be applied to multiple Cleaner objects.

**Describe the solution you'd like**
Something native, TTL/expiration options exposed in the CRDs that the operator could decide when to delete objects. The options that would be nice (imo) are

- TTL/occurences counter (relative to when object added to report)
- Duration (relative to when object added to report)
- Timestamp (absolute)

```go
type ResourceDeleteConditions struct {
	// +kubebuilder:validation:Optional
	Occurrences int `json:"occurrences,omitempty"`

	// +kubebuilder:validation:Optional
	Timestamp *metav1.Time`json:"timestamp,omitempty"`

	// +kubebuilder:validation:Optional
	Duration *metav1.Duration`json:"duration,omitempty"`
}
```

TTL/Occurrences Counter: Configure a max counter in the cleaner. Objects that get written to the Report would have their own counter recorded used later to determine when the object can be deleted.

Every subsequent Cleaner run, the counter would be incremented by 1 if the resource still exists in the report. If the specific resources counter > the `resourceDeleteConditions` then the object would be deleted.

```yaml
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Report
metadata:
  name: cleaner-with-report
spec:
  action: Delete
  resourceDeleteConditions:
    occurrences: 30
  resourceInfo:
  - message: '. time: 2024-04-04 13:25:00.621990728 +0000 UTC m=+227862.774595097'
    firstOccurrence: "2024-04-02T00:25:03Z"
    occurrences: 20 
    resource:
      apiVersion: apps/v1
      kind: Deployment
      name: example
      namespace: example
```

Duration: Record the firstOccurrence timestamp in the resource info, once the duration has elapsed after subsequent runs the object is eligible for deletion and will be removed.

```yaml
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Report
metadata:
  name: cleaner-with-report
spec:
  action: Delete
  resourceDeleteConditions:
    duration: "720h0m0s"
  resourceInfo:
  - message: '. time: 2024-04-04 13:25:00.621990728 +0000 UTC m=+227862.774595097'
    firstOccurrence: "2024-04-02T00:25:03Z"
    occurrences: 20 
    resource:
      apiVersion: apps/v1
      kind: Deployment
      name: example
      namespace: example
```

Timestamp: Absolute, after the given timestamp the objects in the report are deleted.

```yaml
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Report
metadata:
  name: cleaner-with-report
spec:
  action: Delete
  resourceDeleteConditions:
    timestamp: "2024-04-30T00:00:00Z" # <- if the current time is past and the object is still in the report, it should be deleted.
  resourceInfo:
  - message: '. time: 2024-04-03 13:25:00.621990728 +0000 UTC m=+227862.774595097'
    firstOccurrence: "2024-04-02T00:25:03Z"
    occurrences: 20 
    resource:
      apiVersion: apps/v1
      kind: Deployment
      name: example
      namespace: example
```

In the proposed solution it would be possible to combine the conditions as well, where any conditions set must pass for the object in the report to be deleted.

**Describe alternatives you've considered**
Building in the logic to each Cleaner resource and replicating that to multiple Cleaner objects. There are some related examples [here](https://github.com/gianlucam76/k8s-cleaner/tree/main/examples-unused-resources/time_based_delete) but are based on object age or pre-defined annotations on objects which cover a different set of needs than what I am looking for. Technically you could probably create a transform Cleaner to apply metadata to the object such as firstOccurrence or counter and then use that information in a separate Cleaner to delete resources based on duration or # of occurrences but it would be much more tedious and prone to errors.

I think conditional deletion is probably a pretty common use case, people often want some time to verify whether objects should really be deleted so they might use `Scan` first and when they are confident they may create a new cleaner or modify the existing to `Delete`. However when doing so there is no guarantee that the same set of objects as last run would be deleted and different ones may be in the next run. This would give the user an automated way to track & remove resources after specific time related conditions pass.

**Additional context**
I was thinking since the Cleaner Report already tracks objects, it would be relatively simple to store a bit of additional information in the resource list that can be used to determine when the object should be deleted.
