### ISSUE TITLE
unused PVC wrong detection

### ISSUE THREAD

**Issue by jurim76** [gianlucam76/k8s-cleaner#77]
Just FYI
https://github.com/gianlucam76/k8s-cleaner/tree/main/examples-unused-resources/persistent-volume-claims
Using this example, cleaner detected all active PVCs in cluster as unused that is wrong.

**Comment by gianlucam76** [comment]
Thank you @jurim76  for reporting this. I will fix it,verify and push a PR.

Appreciate again you reporting it!

**Comment by gianlucam76** [comment]
Hi @jurim76 can you please give me an example of active PVC that cleaner consider un-used? Thank you.

I am testing with the values [here](https://github.com/gianlucam76/k8s-cleaner/tree/main/internal/controller/executor/validate_aggregatedselection/orphaned_persistent-volume-claims) and there it correctly identifies only one out of two PVCs as un-used.

So clearly I am missing a case and an example of incorrect identification will help me fix this.

Thank you

**Comment by jurim76** [comment]
I've modified the example to use scan every 5 minutes
```
apiVersion: apps.projectsveltos.io/v1alpha1
kind: Cleaner
metadata:
  name: stale-persistent-volume-claim
spec:
  action: Scan
  schedule: "@every 5m"
  notifications:
  - name: report
    type: CleanerReport
  resourcePolicySet:
    resourceSelectors:
    - kind: Pods
      group: ""
      version: v1
    - kind: PersistentVolumeClaim
      group: ""
      version: v1
    aggregatedSelection: |
....
```
Then apply and check the report
```
kubectl get reports.apps.projectsveltos.io stale-persistent-volume-claim -o yaml
```
For example let's check `grafana-db1` PVC from the report
```
  - message: '. time: 2024-06-08 10:31:06.76909835 +0000 UTC m=+300.865260124'
    resource:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: grafana-db1
      namespace: monitoring
```

Check PVC status
```
kubectl -n monitoring get pvc grafana-db1 
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
grafana-db1   Bound    pvc-a80d528f-0c3c-468f-9f74-773258212f9c   4Gi        RWO            topolvm-ext4   17d
```

Check grafana sts
```
kubectl -n monitoring get sts grafana-db1 -o jsonpath='{.spec.template.spec.volumes[*].persistentVolumeClaim}'
{"claimName":"grafana-db1"}
````
grafana-db1 PVC is alive and belongs to grafana-db1 statefulset

Pehaps I missed something and should inerpreter the report output is some other way?
